### ISSUE TITLE
Geonode is watched by easyaudit

### ISSUE THREAD

**Issue by meomancer** [kartoza/LEDET_BIMS#191]
### Problem
When upload layer through geonode, easy audit is watching geonode too. 
```
easyaudit.signals.model_signals ERROR model_signals.py L100: easy audit had a pre-save exception.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/easyaudit/signals/model_signals.py", line 56, in pre_save
    object_json_repr = serializers.serialize("json", [instance])
  File "/usr/local/lib/python2.7/site-packages/django/core/serializers/__init__.py", line 129, in serialize
    s.serialize(queryset, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/serializers/base.py", line 96, in serialize
    self.handle_m2m_field(obj, field)
  File "/usr/local/lib/python2.7/site-packages/django/core/serializers/python.py", line 78, in handle_m2m_field
    m2m_value(related) for related in getattr(obj, field.name).iterator()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 510, in __get__
    return self.related_manager_cls(instance)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 827, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<Layer: ne_10m_admin_0_countries>" needs to have a value for field "id" before this many-to-many relationship can be used.
```

### Solution
Should we ignore geonode by easyaudit?

**Comment by gubuntu** [comment]
I think it's a good thing since we do need to track who does what in the GIS database (see #36; easyaudit might mean we don't have to do that)

1. Does easyaudit track the GIS layer tables themselves or just the django models?
2. Can it be set up to track what goes on in a separate database, since we are likely to separate the DB backend as per #158

**Comment by dimasciput** [comment]
I'm unregistered the audit from the geonode models https://github.com/kartoza/django-bims/pull/154/files#diff-8f2c31233e04d2b684969d23b8182668R175. This also causing error in geonode restore function.

**Comment by gubuntu** [comment]
1. please respond to my comment above or put in new ticket
1. how do we test this or prove it's working?

**Comment by dimasciput** [comment]
@gubuntu the restore geonode is working because I unregistered this one

**Comment by gubuntu** [comment]
We still need easy audit so can you er-enable it now that we've integrated geonode?

**Comment by gubuntu** [comment]
Can we re-enable easy audit without breaking geonode?
